### ISSUE TITLE
(dev) 메인 화면에 캘린더 미노출

### ISSUE THREAD

**Issue by binchoo** [JasonYoo1995/goal_accomplish_friend#1]
[테스트 URL]
http://34.205.25.7:3000/

[재현 과정]
1. 테스트 URL 진입
2. 캘린더 노출 여부 확인

[이슈 내용]
캘린더가 미노출 됩니다

**Comment by binchoo** [comment]
@JasonYoo1995 
Spec out되어 이슈 클로즈합니다. 감사합니다.

**Comment by JasonYoo1995** [comment]
> @JasonYoo1995
> Spec out되어 이슈 클로즈합니다. 감사합니다.

감사합니다
